version: 2
registries:
  npm-registry-agora-dequecloud-com-artifactory-api-npm-dequelabs:
    type: npm-registry
    url: https://agora.dequecloud.com/artifactory/api/npm/dequelabs/
    username: "${{secrets.NPM_REGISTRY_AGORA_DEQUECLOUD_COM_ARTIFACTORY_API_NPM_DEQUELABS_USERNAME}}"
    password: "${{secrets.NPM_REGISTRY_AGORA_DEQUECLOUD_COM_ARTIFACTORY_API_NPM_DEQUELABS_PASSWORD}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: gatsby
    versions:
    - 2.31.1
    - 2.32.0
    - 2.32.1
    - 2.32.10
    - 2.32.11
    - 2.32.2
    - 2.32.3
    - 2.32.4
    - 2.32.6
    - 2.32.8
    - 2.32.9
  - dependency-name: lodash
    versions:
    - 4.17.21
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 2.11.0
    - 2.12.0
  - dependency-name: gatsby-remark-prismjs
    versions:
    - 3.12.0
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.9.0
  registries:
  - npm-registry-agora-dequecloud-com-artifactory-api-npm-dequelabs
